# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    P3P:          CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"

  metas:
    title:        Bahn Gewinnspiel
    description:  Gewinnspiel der Deutschen Bahn
    keywords:     deutsche bahn, gewinnspiel
    language:     de
    robots:       nofollow

  stylesheets:    [http://www.bahn.de/common/view/static/v8/css/bahn.1288860322.min.css, http://www.bahn.de/common/view/static/v8/css/bahn-dyn.1288860322.min.css, main.css]

  javascripts:    [http://www.bahn.de/common/view/static/v8/js/jquery-1.2.6.min.js, http://www.bahn.de/common/view/static/v8/js/bahn.1288860322.min.js, http://www.bahn.de/common/view/static/v8/js/s_code_20100907.js]

  has_layout:     true
  layout:         layout
